// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHtcZcrfwuzbc6Ot31BtZjMsKXP0669Mc',
    appId: '1:918044751759:web:a4675cd1bae66b68847dfa',
    messagingSenderId: '918044751759',
    projectId: 'fir-authentication-base',
    authDomain: 'fir-authentication-base.firebaseapp.com',
    storageBucket: 'fir-authentication-base.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSqLjQftR-sKJzUH5GJrQhHiP2DzIACIc',
    appId: '1:918044751759:android:cc2ef0d080c5951f847dfa',
    messagingSenderId: '918044751759',
    projectId: 'fir-authentication-base',
    storageBucket: 'fir-authentication-base.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9920KxwOxOZ-ja24hWZoUeP9zH1r73Dw',
    appId: '1:918044751759:ios:b2ca23847651cdcf847dfa',
    messagingSenderId: '918044751759',
    projectId: 'fir-authentication-base',
    storageBucket: 'fir-authentication-base.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthenticationBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9920KxwOxOZ-ja24hWZoUeP9zH1r73Dw',
    appId: '1:918044751759:ios:b2ca23847651cdcf847dfa',
    messagingSenderId: '918044751759',
    projectId: 'fir-authentication-base',
    storageBucket: 'fir-authentication-base.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthenticationBase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHtcZcrfwuzbc6Ot31BtZjMsKXP0669Mc',
    appId: '1:918044751759:web:9c90eb7860c0a7d0847dfa',
    messagingSenderId: '918044751759',
    projectId: 'fir-authentication-base',
    authDomain: 'fir-authentication-base.firebaseapp.com',
    storageBucket: 'fir-authentication-base.firebasestorage.app',
  );
}
